---
- name: 'Power ON vms {{poweron_vms_list|join(", ")}}'
  vsphere_guest:
    vcenter_hostname: '{{deploy_vcenter.hostname|mandatory}}'
    username:         '{{vault_vcenter_username|mandatory}}'
    password:         '{{vault_vcenter_password|mandatory}}'
    guest:            '{{vm_name}}'
    validate_certs:   false
    state:            powered_on
  with_items:         '{{poweron_vms_list|default([])|list}}'
  when:
  - poweron_vms_list|default([])|length
  loop_control:
    loop_var: vm_name
