# vim: ts=2 sw=2 et ft=ansible.yaml
---
# validate we have pyvmomi_samples folder indeed
- name: print pyvmomi_samples
  debug:
    msg: '{{pyvmomi_samples}}'
- name: check we have samples dir
  stat:
    path: '{{pyvmomi_samples}}'
  register: pyvmomi_samples_data

- name: validate it is a folder
  assert:
    that: '{{item}}'
  with_items:
  - pyvmomi_samples_data.stat.exists
  - pyvmomi_samples_data.stat.isdir

- name: 'validations for operation={{operation}}'
  include_tasks: 'validate.{{operation}}.yml'
